In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('Master_data')

In [3]:
df.sample()

,Unnamed: 0,resultId,raceId,driverId,constructorId,driver_number,grid,position,positionText,positionOrder,...,nationality_y,url_y,year,round,circuitId,name_y,date,time_y,url,status
4401,4401,4402,224,85,28,23.0,22,NaN,F,22,...,Italian,http://en.wikipedia.org/wiki/Forti,1996,1,1,Australian Grand Prix,1996-03-10,NaN,http://en.wikipedia.org/wiki/1996_Australian_G...,107% Rule

In [4]:
df.describe()

,Unnamed: 0,resultId,raceId,driverId,constructorId,driver_number,grid,position,positionOrder,points,laps,milliseconds,fastestLap,rank,fastestLapSpeed,statusId,year,round,circuitId
count,26758.000000,26758.000000,26758.000000,26758.000000,26758.000000,26752.000000,26758.000000,15805.000000,26758.000000,26758.000000,26758.000000,7.679000e+03,8251.000000,8509.000000,8251.000000,26758.000000,26758.000000,26758.000000,26758.000000
mean,13378.511174,13380.488415,551.665670,278.652926,50.182076,18.154568,11.135137,8.020943,12.794491,1.986772,46.301031,6.185948e+06,42.731548,10.335292,204.114944,17.225577,1991.393153,8.511137,23.821549
std,7724.532727,7725.864948,313.250939,282.688229,61.552133,15.581073,7.202778,4.840627,7.665755,4.349015,29.496862,1.669385e+06,16.604002,6.140653,21.378189,26.026401,19.952262,5.070318,19.111975
min,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,5.260000e+02,1.000000,0.000000,89.540000,1.000000,1950.000000,1.000000,1.000000
25%,6689.250000,6690.250000,300.000000,57.000000,6.000000,7.000000,5.000000,4.000000,6.000000,0.000000,23.000000,5.378620e+06,33.000000,5.000000,193.320000,1.000000,1977.000000,4.000000,9.000000
50%,13378.500000,13379.500000,531.000000,172.000000,25.000000,16.000000,11.000000,8.000000,12.000000,0.000000,53.000000,5.788431e+06,46.000000,10.000000,204.888000,10.000000,1991.000000,8.000000,18.000000
75%,20067.750000,20068.750000,811.000000,399.000000,63.000000,24.000000,17.000000,11.000000,18.000000,2.000000,66.000000,6.403015e+06,54.000000,15.000000,217.328000,14.000000,2009.000000,12.000000,34.000000
max,26758.000000,26764.000000,1144.000000,862.000000,215.000000,208.000000,34.000000,33.000000,39.000000,50.000000,200.000000,1.509054e+07,85.000000,24.000000,257.320000,141.000000,2024.000000,24.000000,80.000000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26758 entries, 0 to 26757
Data columns (total 37 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          26758 non-null  int64
 1   resultId            26758 non-null  int64
 2   raceId              26758 non-null  int64
 3   driverId            26758 non-null  int64
 4   constructorId       26758 non-null  int64
 5   driver_number       26752 non-null  float64
 6   grid                26758 non-null  int64
 7   position            15805 non-null  float64
 8   positionText        26758 non-null  object
 9   positionOrder       26758 non-null  int64
 10  points              26758 non-null  float64
 11  laps                26758 non-null  int64
 12  milliseconds        7679 non-null   float64
 13  fastestLap          8251 non-null   float64
 14  rank                8509 non-null   float64
 15  fastestLapTime      8251 non-null   object
 16  fastestLapSpeed     8251 non-null   float64
 17  statusId            26758 non-null  int64
 18  driverRef           26758 non-null  object
 19  code                10177 non-null  object
 20  forename            26758 non-null  object
 21  surname             26758 non-null  object
 22  dob                 26758 non-null  object
 23  driver_nationality  26758 non-null  object
 24  driver_url          26758 non-null  object
 25  constructorRef      26758 non-null  object
 26  name_x              26758 non-null  object
 27  nationality_y       26758 non-null  object
 28  url_y               26758 non-null  object
 29  year                26758 non-null  int64
 30  round               26758 non-null  int64
 31  circuitId           26758 non-null  int64
 32  name_y              26758 non-null  object
 33  date                26758 non-null  object
 34  time_y              8289 non-null   object
 35  url                 26758 non-null  object
 36  status              26758 non-null  object
dtypes: float64(7), int64(12), object(18)
memory usage: 7.6+ MB

In [6]:
df.shape

(26758, 37)

In [7]:
df = df.sort_values(by=['year','round'], ascending=[True,True])

In [8]:
df['driver_form_3_races'] = (
    df.groupby('driverId')['points']
    .transform(lambda x: x.rolling(window=3, min_periods=1).sum().shift(1))
)

In [9]:
print(df[df['driverId'] == 1][['year', 'round', 'points', 'driver_form_3_races']].tail(10))

       year  round  points  driver_form_3_races
26565  2024     15     4.0                 65.0
26582  2024     16    10.0                 44.0
26606  2024     17     2.0                 39.0
26623  2024     18     8.0                 16.0
26657  2024     19     0.0                 20.0
26661  2024     20    12.0                 10.0
26687  2024     21     1.0                 20.0
26699  2024     22    18.0                 13.0
26729  2024     23     0.0                 31.0
26741  2024     24    12.0                 19.0

In [10]:
# Group by the Team, calculate the 3-race rolling sum, and shift by 1
df['team_form_3_races'] = (
    df.groupby('constructorId')['points']
    .transform(lambda x: x.rolling(window=3, min_periods=1).sum().shift(1))
)

In [11]:
df.grid

20024     1
20025     2
20026     4
20027     6
20028     9
         ..
26753    14
26754    12
26755     9
26756    20
26757    10
Name: grid, Length: 26758, dtype: int64

In [12]:
df['grid'] = np.where(df['grid'] == 0, 20, df['grid'])

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 26758 entries, 20024 to 26757
Data columns (total 39 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           26758 non-null  int64
 1   resultId             26758 non-null  int64
 2   raceId               26758 non-null  int64
 3   driverId             26758 non-null  int64
 4   constructorId        26758 non-null  int64
 5   driver_number        26752 non-null  float64
 6   grid                 26758 non-null  int64
 7   position             15805 non-null  float64
 8   positionText         26758 non-null  object
 9   positionOrder        26758 non-null  int64
 10  points               26758 non-null  float64
 11  laps                 26758 non-null  int64
 12  milliseconds         7679 non-null   float64
 13  fastestLap           8251 non-null   float64
 14  rank                 8509 non-null   float64
 15  fastestLapTime       8251 non-null   object
 16  fastestLapSpeed      8251 non-null   float64
 17  statusId             26758 non-null  int64
 18  driverRef            26758 non-null  object
 19  code                 10177 non-null  object
 20  forename             26758 non-null  object
 21  surname              26758 non-null  object
 22  dob                  26758 non-null  object
 23  driver_nationality   26758 non-null  object
 24  driver_url           26758 non-null  object
 25  constructorRef       26758 non-null  object
 26  name_x               26758 non-null  object
 27  nationality_y        26758 non-null  object
 28  url_y                26758 non-null  object
 29  year                 26758 non-null  int64
 30  round                26758 non-null  int64
 31  circuitId            26758 non-null  int64
 32  name_y               26758 non-null  object
 33  date                 26758 non-null  object
 34  time_y               8289 non-null   object
 35  url                  26758 non-null  object
 36  status               26758 non-null  object
 37  driver_form_3_races  25897 non-null  float64
 38  team_form_3_races    26547 non-null  float64
dtypes: float64(9), int64(12), object(18)
memory usage: 8.2+ MB

In [14]:
columns_to_fill = ['driver_form_3_races', 'team_form_3_races']

df[columns_to_fill] = df[columns_to_fill].fillna(0)

print("Missing values in momentum columns:")
print(df[columns_to_fill].isnull().sum())

Missing values in momentum columns:
driver_form_3_races    0
team_form_3_races      0
dtype: int64

In [15]:
df = pd.get_dummies(df, columns=['constructorRef'], drop_first=True)

In [16]:
df

,Unnamed: 0,resultId,raceId,driverId,constructorId,driver_number,grid,position,positionText,positionOrder,...,constructorRef_tyrrell,constructorRef_vanwall,constructorRef_veritas,constructorRef_vhristensen,constructorRef_virgin,constructorRef_watson,constructorRef_wetteroth,constructorRef_williams,constructorRef_wolf,constructorRef_zakspeed
20024,20024,20025,833,642,51,2.0,1,1.0,1,1,...,False,False,False,False,False,False,False,False,False,False
20025,20025,20026,833,786,51,3.0,2,2.0,2,2,...,False,False,False,False,False,False,False,False,False,False
20026,20026,20027,833,686,51,4.0,4,3.0,3,3,...,False,False,False,False,False,False,False,False,False,False
20027,20027,20028,833,704,154,14.0,6,4.0,4,4,...,False,False,False,False,False,False,False,False,False,False
20028,20028,20029,833,627,154,15.0,9,5.0,5,5,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26753,26754,26760,1144,825,210,20.0,14,16.0,16,16,...,False,False,False,False,False,False,False,False,False,False
26754,26755,26761,1144,859,215,30.0,12,17.0,17,17,...,False,False,False,False,False,False,False,False,False,False
26755,26756,26762,1144,822,15,77.0,9,NaN,R,18,...,False,False,False,False,False,False,False,False,False,False
26756,26757,26763,1144,861,3,43.0,20,NaN,R,19,...,False,False,False,False,False,False,False,True,False,False
26757,26758,26764,1144,815,9,11.0,10,NaN,R,20,...,False,False,False,False,False,False,False,False,False,False

In [17]:
train_df = df[df['year'] < 2023]
test_df = df[df['year'] >= 2023]

columns_to_drop = ['positionOrder', 'position', 'resultId', 'raceId', 'driverId', 'constructorId']

X_train = train_df.drop(columns=columns_to_drop, errors='ignore')
y_train = train_df['positionOrder']

X_test = test_df.drop(columns=columns_to_drop, errors='ignore')
y_test = test_df['positionOrder']

# 3. The Audit
print("Training Clues Shape (Past):", X_train.shape)
print("Testing Clues Shape (Future):", X_test.shape)

Training Clues Shape (Past): (25840, 242)
Testing Clues Shape (Future): (918, 242)

In [18]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

cols_to_scale = ['year', 'round', 'grid', 'driver_form_3_races', 'team_form_3_races']

X_train[cols_to_scale] = scaler.fit_transform(X_train[cols_to_scale])
X_test[cols_to_scale] = scaler.transform(X_test[cols_to_scale])

In [19]:
# X_train = X_train.drop(columns=['positionText'], errors='ignore')
# X_test = X_test.drop(columns=['positionText'], errors='ignore')

# Target the specific column and replace 'R' with the number 20
df['positionText'] = df['positionText'].replace('R', 20)

# You can also chain this to catch other text anomalies in that column!
df['positionText'] = df['positionText'].replace({'W': 20, 'D': 20})

In [20]:
from sklearn.linear_model import LinearRegression

# f1_model = LinearRegression()

# f1_model.fit(X_train, y_train)

In [21]:
# This scans the dataframe and prints a list of ONLY the text columns
text_columns = df.select_dtypes(include=['object']).columns.tolist()

print("These columns are text (objects) and will crash the AI:")
print(text_columns)

These columns are text (objects) and will crash the AI:
['positionText', 'fastestLapTime', 'driverRef', 'code', 'forename', 'surname', 'dob', 'driver_nationality', 'driver_url', 'name_x', 'nationality_y', 'url_y', 'name_y', 'date', 'time_y', 'url', 'status']

In [22]:
print(df.dtypes=='object')

Unnamed: 0                  False
resultId                    False
raceId                      False
driverId                    False
constructorId               False
                            ...
constructorRef_watson       False
constructorRef_wetteroth    False
constructorRef_williams     False
constructorRef_wolf         False
constructorRef_zakspeed     False
Length: 248, dtype: bool

In [23]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score
import pandas as pd

# 1. The Senior Filter: Keep only math-safe columns
X_train_clean = X_train.select_dtypes(exclude=['object'])
X_test_clean = X_test.select_dtypes(exclude=['object'])

# 2. THE GLOBAL IMPUTER (CRITICAL FIX): Plug all remaining blank spaces with 0
X_train_clean = X_train_clean.fillna(0)
X_test_clean = X_test_clean.fillna(0)

# 3. Initialize the Model
f1_model = LinearRegression()

# 4. Train the AI (The Study Session)
print("Training the AI on historical data...")
f1_model.fit(X_train_clean, y_train)

# 5. Predict the Future (The Final Exam)
print("Predicting the 2023 season...")
predictions = f1_model.predict(X_test_clean)

# 6. Grade the AI's Performance
mae = mean_absolute_error(y_test, predictions)
r2 = r2_score(y_test, predictions)

print("\n--- The Results ---")
print(f"Mean Absolute Error (MAE): {mae:.2f} positions")
print(f"R-squared Score: {r2:.2f}")

# Peek at the first 5 predictions vs reality!
results_df = pd.DataFrame({'Actual Position': y_test.head(), 'Predicted Position': predictions[:5]})
print("\nFirst 5 Predictions vs Reality:")
print(results_df)

Training the AI on historical data...
Predicting the 2023 season...

--- The Results ---
Mean Absolute Error (MAE): 3.14 positions
R-squared Score: -0.01

First 5 Predictions vs Reality:
       Actual Position  Predicted Position
25840                1           -1.874350
25841                2            0.818402
25842                3            0.928372
25843                4            4.960982
25844                5            6.833904