In [33]:
import pandas as pd
import numpy as np

In [34]:
df = pd.read_csv('../data/training_data/IPL.csv')

C:\Users\Kartik\AppData\Local\Temp\ipykernel_18696\2496289093.py:1: DtypeWarning: Columns (0: review_batter, 1: team_reviewed, 2: review_decision, 3: umpire, 4: season, 5: superover_winner, 6: result_type, 7: method, 8: event_match_no) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../data/training_data/IPL.csv')

In [35]:
df.shape

(283678, 65)

In [36]:
# data.duplicated().sum()

In [37]:
df.sample(5)

,Unnamed: 0,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,...,team_balls,team_wicket,new_batter,power_surge_start,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
203424,65384,1254092,2021-09-28,T20,Indian Premier League,2,Kolkata Knight Riders,Delhi Capitals,4,5,...,29,1,NaN,NaN,6,2,0,"('RA Tripathi', 'Shubman Gill')",NaN,False
108984,250591,829705,2015-04-08,T20,Indian Premier League,2,Kolkata Knight Riders,Mumbai Indians,1,6,...,12,0,NaN,NaN,1,4,0,"('G Gambhir', 'RV Uthappa')",NaN,False
60441,202048,548313,2012-04-08,T20,Indian Premier League,2,Kings XI Punjab,Pune Warriors,19,1,...,115,8,P Kumar,NaN,24,15,0,"('Bipul Sharma', 'P Kumar')",NaN,False
182065,45135,1216503,2020-10-01,T20,Indian Premier League,1,Mumbai Indians,Kings XI Punjab,5,3,...,33,2,NaN,NaN,19,15,0,"('Ishan Kishan', 'RG Sharma')",NaN,False
144306,7708,1082624,2017-04-29,T20,Indian Premier League,1,Rising Pune Supergiant,Royal Challengers Bangalore,18,1,...,109,3,NaN,NaN,32,28,0,"('MK Tiwary', 'MS Dhoni')",NaN,False

In [38]:
df.columns

Index(['Unnamed: 0', 'match_id', 'date', 'match_type', 'event_name', 'innings',
       'batting_team', 'bowling_team', 'over', 'ball', 'ball_no', 'batter',
       'bat_pos', 'runs_batter', 'balls_faced', 'bowler', 'valid_ball',
       'runs_extras', 'runs_total', 'runs_bowler', 'runs_not_boundary',
       'extra_type', 'non_striker', 'non_striker_pos', 'wicket_kind',
       'player_out', 'fielders', 'runs_target', 'review_batter',
       'team_reviewed', 'review_decision', 'umpire', 'umpires_call',
       'player_of_match', 'match_won_by', 'win_outcome', 'toss_winner',
       'toss_decision', 'venue', 'city', 'day', 'month', 'year', 'season',
       'gender', 'team_type', 'superover_winner', 'result_type', 'method',
       'balls_per_over', 'overs', 'event_match_no', 'stage', 'match_number',
       'team_runs', 'team_balls', 'team_wicket', 'new_batter',
       'power_surge_start', 'batter_runs', 'batter_balls', 'bowler_wicket',
       'batting_partners', 'next_batter', 'striker_out'],
      dtype='str')

In [39]:
df.match_won_by.sample(7)

25869     Chennai Super Kings
269054         Gujarat Titans
170943         Delhi Capitals
253900           Punjab Kings
3813         Delhi Daredevils
61842         Kings XI Punjab
229861       Rajasthan Royals
Name: match_won_by, dtype: str

In [40]:
# Filter only innings 1, group by match_id, take batting_team
team1 = df[df['innings'] == 1].groupby('match_id')['batting_team'].first()
team2 = df[df['innings'] == 2].groupby('match_id')['batting_team'].first()

In [41]:
df.head()

,Unnamed: 0,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,...,team_balls,team_wicket,new_batter,power_surge_start,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
0,141607,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,...,1,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
1,141608,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,...,2,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
2,141609,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,2,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
3,141610,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,3,0,NaN,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False
4,141611,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,...,4,0,NaN,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False

In [42]:
# match_id, date, venue, city, season, batting_team, bowling_team, toss_winner, toss_decision, match_won_by
# 'Unnamed: 0', 'match_id', 'date', 'match_type', 'event_name', 'innings',
#        'batting_team', 'bowling_team', 'over', 'ball', 'ball_no', 'batter',
#        'bat_pos', 'runs_batter', 'balls_faced', 'bowler', 'valid_ball',
#        'runs_extras', 'runs_total', 'runs_bowler', 'runs_not_boundary',
#        'extra_type', 'non_striker', 'non_striker_pos', 'wicket_kind',
#        'player_out', 'fielders', 'runs_target', 'review_batter',
#        'team_reviewed', 'review_decision', 'umpire', 'umpires_call',
#        'player_of_match', 'match_won_by', 'win_outcome', 'toss_winner',
#        'toss_decision', 'venue', 'city', 'day', 'month', 'year', 'season',
#        'gender', 'team_type', 'superover_winner', 'result_type', 'method',
#        'balls_per_over', 'overs', 'event_match_no', 'stage', 'match_number',
#        'team_runs', 'team_balls', 'team_wicket', 'new_batter',
#        'power_surge_start', 'batter_runs', 'batter_balls', 'bowler_wicket',
#        'batting_partners', 'next_batter', 'striker_out'

In [43]:
# df = df.drop(columns=['Unnamed: 0', 'match_type', 'event_name', 'innings', 'over', 'ball', 'ball_no', 'batter','bat_pos', 'runs_batter', 'balls_faced', 'bowler', 'valid_ball','runs_extras', 'runs_total', 'runs_bowler', 'runs_not_boundary','extra_type', 'non_striker', 'non_striker_pos', 'wicket_kind','player_out', 'fielders', 'runs_target', 'review_batter','team_reviewed', 'review_decision', 'umpire', 'umpires_call','player_of_match', 'win_outcome', 'day', 'month', 'year','gender', 'team_type', 'superover_winner', 'result_type', 'method','balls_per_over', 'overs', 'event_match_no', 'stage', 'match_number','team_runs', 'team_balls', 'team_wicket', 'new_batter','power_surge_start', 'batter_runs', 'batter_balls', 'bowler_wicket','batting_partners', 'next_batter', 'striker_out'])
cols_to_keep = ['match_id', 'date', 'venue', 'city', 'season', 'batting_team', 'bowling_team', 'toss_winner', 'toss_decision', 'match_won_by']
df = df[cols_to_keep]

In [44]:
grouped_df = df.groupby('match_id').first()

In [45]:
grouped_df.sample()

,date,venue,city,season,batting_team,bowling_team,toss_winner,toss_decision,match_won_by
match_id,,,,,,,,,
1082607,2017-04-16,M Chinnaswamy Stadium,Bangalore,2017,Rising Pune Supergiant,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Rising Pune Supergiant

In [46]:
grouped_df.shape

(1193, 9)

In [47]:
print(grouped_df.columns.tolist())
print(grouped_df.isnull().sum())

['date', 'venue', 'city', 'season', 'batting_team', 'bowling_team', 'toss_winner', 'toss_decision', 'match_won_by']
date             0
venue            0
city             0
season           0
batting_team     0
bowling_team     0
toss_winner      0
toss_decision    0
match_won_by     0
dtype: int64

In [48]:
grouped_df.dtypes

date                str
venue               str
city                str
season           object
batting_team        str
bowling_team        str
toss_winner         str
toss_decision       str
match_won_by        str
dtype: object

In [49]:
print(team1.head())
print(team2.head())
print(type(team1))

match_id
335982    Kolkata Knight Riders
335983      Chennai Super Kings
335984         Rajasthan Royals
335985           Mumbai Indians
335986          Deccan Chargers
Name: batting_team, dtype: str
match_id
335982    Royal Challengers Bangalore
335983                Kings XI Punjab
335984               Delhi Daredevils
335985    Royal Challengers Bangalore
335986          Kolkata Knight Riders
Name: batting_team, dtype: str
<class 'pandas.Series'>

In [50]:
grouped_df['team1'] = team1
grouped_df['team2'] = team2

In [51]:
grouped_df.shape

(1193, 11)

In [52]:
grouped_df.sample()

,date,venue,city,season,batting_team,bowling_team,toss_winner,toss_decision,match_won_by,team1,team2
match_id,,,,,,,,,,,
1178393,2019-04-06,MA Chidambaram Stadium,Chennai,2019,Chennai Super Kings,Kings XI Punjab,Chennai Super Kings,bat,Chennai Super Kings,Chennai Super Kings,Kings XI Punjab

In [53]:
grouped_df['match_won_by'].value_counts()

match_won_by
Mumbai Indians                 152
Chennai Super Kings            144
Kolkata Knight Riders          135
Rajasthan Royals               118
Royal Challengers Bangalore    114
Sunrisers Hyderabad             95
Kings XI Punjab                 85
Delhi Daredevils                67
Delhi Capitals                  53
Gujarat Titans                  39
Punjab Kings                    38
Lucknow Super Giants            32
Deccan Chargers                 29
Unknown                         24
Royal Challengers Bengaluru     22
Gujarat Lions                   13
Pune Warriors                   12
Rising Pune Supergiant          10
Kochi Tuskers Kerala             6
Rising Pune Supergiants          5
Name: count, dtype: int64

In [54]:
grouped_df['match_won_by'] = grouped_df['match_won_by'].replace({'Royal Challengers Bengaluru':'Royal Challengers Bangalore' , 'Rising Pune Supergiants':'Rising Pune Supergiant' , 'Pune Warriors':'Rising Pune Supergiant' , 'Gujarat Lions':'Gujarat Titans' , 'Punjab Kings':'Kings XI Punjab' , 'Delhi Daredevils':'Delhi Capitals' })

In [55]:
grouped_df['match_won_by'].value_counts()

match_won_by
Mumbai Indians                 152
Chennai Super Kings            144
Royal Challengers Bangalore    136
Kolkata Knight Riders          135
Kings XI Punjab                123
Delhi Capitals                 120
Rajasthan Royals               118
Sunrisers Hyderabad             95
Gujarat Titans                  52
Lucknow Super Giants            32
Deccan Chargers                 29
Rising Pune Supergiant          27
Unknown                         24
Kochi Tuskers Kerala             6
Name: count, dtype: int64

In [56]:
grouped_df = grouped_df[grouped_df['match_won_by'] !='Unknown']

In [57]:
grouped_df['match_won_by'].value_counts()

match_won_by
Mumbai Indians                 152
Chennai Super Kings            144
Royal Challengers Bangalore    136
Kolkata Knight Riders          135
Kings XI Punjab                123
Delhi Capitals                 120
Rajasthan Royals               118
Sunrisers Hyderabad             95
Gujarat Titans                  52
Lucknow Super Giants            32
Deccan Chargers                 29
Rising Pune Supergiant          27
Kochi Tuskers Kerala             6
Name: count, dtype: int64

In [58]:
print(grouped_df.shape)
print(grouped_df['match_won_by'].value_counts())

(1169, 11)
match_won_by
Mumbai Indians                 152
Chennai Super Kings            144
Royal Challengers Bangalore    136
Kolkata Knight Riders          135
Kings XI Punjab                123
Delhi Capitals                 120
Rajasthan Royals               118
Sunrisers Hyderabad             95
Gujarat Titans                  52
Lucknow Super Giants            32
Deccan Chargers                 29
Rising Pune Supergiant          27
Kochi Tuskers Kerala             6
Name: count, dtype: int64

In [59]:
print(grouped_df['team1'].value_counts())

team1
Mumbai Indians                 143
Chennai Super Kings            140
Kolkata Knight Riders          126
Royal Challengers Bangalore    117
Sunrisers Hyderabad            107
Rajasthan Royals               106
Kings XI Punjab                 96
Delhi Daredevils                69
Deccan Chargers                 43
Delhi Capitals                  43
Punjab Kings                    40
Lucknow Super Giants            35
Gujarat Titans                  29
Pune Warriors                   20
Royal Challengers Bengaluru     20
Gujarat Lions                   13
Rising Pune Supergiant           8
Kochi Tuskers Kerala             7
Rising Pune Supergiants          7
Name: count, dtype: int64

In [60]:
team_name_mapping = {
    'Royal Challengers Bengaluru': 'Royal Challengers Bangalore',
    'Punjab Kings': 'Kings XI Punjab',
    'Rising Pune Supergiants': 'Rising Pune Supergiant',
    'Delhi Daredevils': 'Delhi Capitals',
}

# Now apply to all columns
for col in ['batting_team', 'bowling_team', 'team1', 'team2', 'match_won_by', 'toss_winner']:
    grouped_df[col] = grouped_df[col].replace(team_name_mapping)

In [61]:
grouped_df = grouped_df.drop(columns=['date', 'batting_team', 'bowling_team','city'])

In [62]:
print(grouped_df.columns.to_list())
print(grouped_df.shape)

['venue', 'season', 'toss_winner', 'toss_decision', 'match_won_by', 'team1', 'team2']
(1169, 7)

In [63]:
grouped_df.dtypes

venue               str
season           object
toss_winner         str
toss_decision       str
match_won_by        str
team1               str
team2               str
dtype: object

In [64]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

cols_to_encode = ['venue','toss_winner', 'toss_decision', 'team1', 'team2', 'match_won_by']

KeyboardInterrupt:

In [ ]:
label_encoders = {}

for col in cols_to_encode:
    le = LabelEncoder()
    grouped_df[col] = le.fit_transform(grouped_df[col])
    label_encoders[col] = le

In [ ]:
grouped_df.sample()

In [ ]:
grouped_df = grouped_df['season'].str[:4].astype(int)
# grouped_df.isna().sum()

In [ ]:
print(type(grouped_df))
print(grouped_df.shape)